//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.05 at 06:40:32 PM IST 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://allstate.com/claim", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.allstate.restclaimwebservice.model;
