//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.06.08 at 12:56:45 PM IST 
//


package com.allstate.restclaimwebservice.model;

import jakarta.xml.bind.annotation.*;


/**
 * <p>Java class for anonymous complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="PolicyDetails" type="{http://allstate.com/soapclaimwebservice/model}PolicyDetails"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
        "policyDetails"
})
@XmlRootElement(name = "GetPolicyDetailsResponse")
public class PolicyDetailsResponse {

    @XmlElement(name = "PolicyDetails", required = true)
    protected PolicyDetails policyDetails;

    /**
     * Gets the value of the policyDetails property.
     *
     * @return possible object is
     * {@link PolicyDetails }
     */
    public PolicyDetails getPolicyDetails() {
        return policyDetails;
    }

    /**
     * Sets the value of the policyDetails property.
     *
     * @param value allowed object is
     *              {@link PolicyDetails }
     */
    public void setPolicyDetails(PolicyDetails value) {
        this.policyDetails = value;
    }

}
